FROM alpine:3.18 AS builder
WORKDIR /build

RUN wget -O dalamud.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
RUN unzip dalamud.zip -d dalamud

# ---------------------

FROM mcr.microsoft.com/dotnet/runtime:7.0-bullseye-slim
ENV DALAMUD_HOME=/lib/dalamud
WORKDIR ${DALAMUD_HOME}

COPY --from=builder /build/dalamud/ ${DALAMUD_HOME}/